---
- name: Check if Nginx container is running
  docker_container_info:
    name: nginx_container
  register: nginx_container_running
  ignore_errors: yes

- name: Stop Nginx container if running
  docker_container:
    name: nginx_container
    state: stopped
  when: nginx_container_running is defined and nginx_container_running.containers | length > 0

- name: Remove Nginx container if it exists
  docker_container:
    name: nginx_container
    state: absent
  when: nginx_container_running is defined and nginx_container_running.containers | length > 0

- name: Pull Nginx image from Docker Hub
  docker_image:
    name: "{{ docker_image }}"
    pull: yes

- name: Create and run Nginx container with parameters
  docker_container:
    name: nginx_container
    image: "{{ docker_image }}"
    state: started
    ports:
      - "{{ docker_host_port }}:{{ docker_port }}"
    volumes:
      - "{{ docker_volume }}"
