---
- name: Check if nginx container is running
  shell: sudo docker ps -a
  register: nginx_container_running
  ignore_errors: yes

- name: Stop nginx container if running
  shell: sudo docker stop nginx_container
  ignore_errors: yes
  when: nginx_container_running is defined and nginx_container_running.rc == 0

- name: Remove nginx container if it exists
  shell: sudo docker rm nginx_container
  when: nginx_container_running.rc == 0

- name: Pull nginx image from Docker Hub
  command: sudo docker pull {{ docker_image }}

- name: Create and run nginx container with parameters
  command: >
    sudo docker run -d
    -p {{ docker_host_port }}:{{ docker_port }}
    --name nginx_container
    -v {{ docker_volume }}
    {{ docker_image }}
